### ISSUE TITLE
License

### ISSUE THREAD

**Issue by akinomeroglu** [sixfab/tinylab#1]
Hi,

I notice your project in indiegogo. You mention that license is CC-BY-SA in campaign website. As far as I see in license file it is licensed under CC-BY not CC-BY-SA.

So can you clarify that which license is valid for project.

Thanks,

**Comment by selengalp** [comment]
Merhaba,

Bahsettiğiniz konuyu tekrar inceledik. Gerekli düzenlemeyi gerçekleştirdik. İlginiz için teşekkür ederiz.

Saygılar,
