### ISSUE TITLE
Serial1 was not declared

### ISSUE THREAD

**Issue by Smus** [sixfab/tinylab#8]
Hi

im getting:
twitter:45: error: 'Serial1' was not declared in this scope
   Serial1.begin(115200); 

any ideas?

**Comment by selengalp** [comment]
Please check out your selected arduino board? If you selected any other board from arduino leonardo, you would probably get this compilation error.

**Comment by sjkim04** [comment]
Um........ I think you don't need '1'.
And.... this is an advice.
In the Epalsite Electronics pdf, to begin serial, you need to type:
Serial.begin(9600)
